### PR TITLE
feat: add trade details history

### PR DESCRIPTION
**Pull request by sfmqrb**
#214

### CODE REVIEW

**Comment by sfmqrb** [comment]
executing the following IO-intensive code with no problem

```python
import pytse_client as tse
from datetime import date

start_date = date(2000, 3, 19)
end_date = date(2023, 4, 22)
symbol = "خودرو"

df = tse.get_trade_details(
    symbol, start_date, end_date, to_csv=True, aggregate=True, timeframe='1m'
)
print(df)
```

**Comment by sfmqrb** [comment]
@Glyphack Please check this out.

**Comment by Glyphack** [comment]
> @Glyphack Please check this out.

Will do today

**Comment by Glyphack** [comment]
I couldn't check this, will be back next week

**Pull request merged**
